### ISSUE TITLE
Cannot bootstrap project without typescript

### ISSUE THREAD

**Issue by ckeeney** [d4rkr00t/opaline#23]
The bootstrap process asks "Use Typescript?" and defaults to yes.  If you choose no, the bootstrap process crashes with 
```
Cannot set property 'lint-staged' of undefined
```

and the `package.json` file generated contains 

```
{
  "name": "cj-cli",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```

![image](https://user-images.githubusercontent.com/8799010/157783593-153370cb-2ae7-4615-ad3c-a66d1b3e2f0f.png)

**Comment by d4rkr00t** [comment]
Fixed here: https://github.com/d4rkr00t/opaline/commit/4d4733522f823d9917ae4553cc8f9770205a2dc5 will release a new version soon. Thanks for raising this.
