### ISSUE TITLE
Possible to package up executable for distribution?

### ISSUE THREAD

**Issue by austinfox** [d4rkr00t/opaline#8]
First off, this is an awesome tool, thanks for making it available. I was playing around with it and its very easy to use. That said, is there a way to package up the generated executables in a way that they can be distributed without dependencies or a need to run npm install? This might not be the intended goal of the project, but I think it would be a really useful feature to have.

**Comment by d4rkr00t** [comment]
Hi, 
Thanks for the feedback!

It's already possible using https://github.com/zeit/pkg. But since it runs in nodejs. Executable needs to include it as well, which means that a hello world binary is around 70mb :( 

```sh
npx @opaline/core create app && cd app && npm install && npm run build
npx pkg dist/cli.js
ls -la

.rwxr-xr-x 72M user 18 Apr 12:28 cli-linux*
.rwxr-xr-x 70M user 18 Apr 12:28 cli-macos*
.rw-r--r-- 69M user 18 Apr 12:28 cli-win.exe
```

Not sure if it's possible to make it smaller, maybe there are some smaller JS runtimes?

**Comment by v1rtl** [comment]
I think it would be easy to implement with using [pkg](https://github.com/zeit/pkg). It has a programmable API so it is easy to write a command for that.

Other builder I found: https://github.com/nexe/nexe

**Comment by d4rkr00t** [comment]
IMHO it's literally 2 lines change in `package.json`:

```diff
"dependencies": {
...
+"pkg": "*",
...
},
"scripts": {
...
+ "pkg": "npm run build && pkg dist/cli.js"
...
}
```

And also because of the runtime size I don't think it's a viable option for the CLIt tools that Opaline is trying to target, at least for most of them. Hence it doesn't make sense to have it as a built-in feature.
